"""add ai_plan column to usewssd

Revision ID: 7418ce7b627a
Revises: 45c5d23ccb20
Create Date: 2026-02-15 22:31:09.094944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7418ce7b627a'
down_revision: Union[str, Sequence[str], None] = '45c5d23ccb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
