"""add ai_plan column to user_profiles

Revision ID: c76c369b8d86
Revises: 541814fa0fbb
Create Date: 2026-02-15 22:11:51.821867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76c369b8d86'
down_revision: Union[str, Sequence[str], None] = '541814fa0fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('ai_plan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'ai_plan')
    # ### end Alembic commands ###
